# Generated by Django 6.0.4 on 2026-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotor',
            name='telefono',
            field=models.CharField(default=33567890, max_length=12),
            preserve_default=False,
        ),
    ]
