# Generated by Django 6.0.4 on 2026-05-12 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_evento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='crear_evento.evento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='usuarios.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_evento', 'fecha'), name='uq_historial_usuario_evento_fecha')],
            },
        ),
    ]
