# Generated by Django 6.0.4 on 2026-05-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_evento', '0003_alter_evento_categoria_alter_evento_promotor'),
        ('usuarios', '0001_initial'),
        ('ver_evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='crear_evento.evento'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='usuarios.usuario'),
        ),
    ]
