# Generated by Django 6.0.4 on 2026-05-12 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_evento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_promotor', to='usuarios.promotor'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario',
            field=models.ManyToManyField(related_name='evento_horario', to='crear_evento.horario'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('cupo__gte', 0)), name='chk_evento_cupo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('costo__gte', 0)), name='chk_evento_costo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='chk_evento_fechas_validas'),
        ),
    ]
