# Generated by Django 6.0.4 on 2026-05-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_evento', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento_categoria', to='crear_evento.categoria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento_promotor', to='usuarios.promotor'),
        ),
    ]
