# Generated by Django 6.0.4 on 2026-05-20 20:48

import crear_evento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_evento', '0003_alter_evento_categoria_alter_evento_promotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=crear_evento.models.ruta_imagen_evento),
        ),
    ]
